### ISSUE TITLE
Record physiology and eye tracking during the DWI run

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#112]
Including the following two task:
- [ ] Adapt the instructions given to the participant during DWI in the SOPs
- [ ] Create the corresponding psychopy experiment file
- [ ] Update task duration in the SOPs
