### ISSUE TITLE
Eye tracker 'SR Research Ltd' not found in new version of psychopy

### ISSUE THREAD

**Issue by esavary** [TheAxonLab/hcph-sops#253]
Traceback (most recent call last):
  File "/home/common/.local/lib/python3.10/site-packages/psychopy/app/builder/builder.py", line 1275, in runFile
    self.app.runner.panel.runLocal(event)
  File "/home/common/.local/lib/python3.10/site-packages/psychopy/app/runner/runner.py", line 749, in runLocal
    generateScript(experimentPath=currentFile.replace('.psyexp', '_lastrun.py'),
  File "/home/common/.local/lib/python3.10/site-packages/psychopy/scripts/psyexpCompile.py", line 91, in generateScript
    compileScript(infile=exp, version=None, outfile=filename)
  File "/home/common/.local/lib/python3.10/site-packages/psychopy/scripts/psyexpCompile.py", line 229, in compileScript
    _makeTarget(thisExp, outfile, targetOutput)
  File "/home/common/.local/lib/python3.10/site-packages/psychopy/scripts/psyexpCompile.py", line 209, in _makeTarget
    script = thisExp.writeScript(outfile, target=targetOutput)
  File "/home/common/.local/lib/python3.10/site-packages/psychopy/experiment/_experiment.py", line 297, in writeScript
    self_copy.settings.writeIohubCode(script)
  File "/home/common/.local/lib/python3.10/site-packages/psychopy/experiment/components/settings/__init__.py", line 1274, in writeIohubCode
    inits['eyetracker'].val = ioDeviceMap[inits['eyetracker'].val]
KeyError: 'SR Research Ltd'

**Comment by esavary** [comment]
@oesteban, I attempted to use Psychopy in the common user session, as it wasn't functioning in my own session. I noticed that you've already installed the branch with your fixes for the eyetracker. Are there any additional steps I should take before using it?
@acionca, is this the same issue you encountered last week? If so, did you discover a solution that's more efficient than reinstalling everything?

**Comment by esavary** [comment]
I'll go ahead and reinstall everything in my session since I need to make modifications to the tasks and ensure we have something able to run them for our session on Thursday. However, if there's a more efficient solution available for the common user session, I'm certainly interested in exploring that option.

**Comment by acionca** [comment]
> @acionca, is this the same issue you encountered last week? If so, did you discover a solution that's more efficient than reinstalling everything?

Indeed, I had the same issue - since I only wanted to test the tasks, I fixed it by using MouseGaze (which, I believe, is not what you want here). It never worked for me otherwise.

**Comment by esavary** [comment]
It seems not to work when the ET is plugged, too, but maybe I missed a step. Indeed, for the acquisitions, we need the actual ET.

**Comment by esavary** [comment]
I believe @oesteban tested it was working at CHUV on Friday so I probably missed something.

**Comment by acionca** [comment]
I believe @oesteban mentioned that it should also be working without the ET plugged

**Comment by esavary** [comment]
Yes, I think it was solved with https://github.com/oesteban/psychopy-eyetracker-eyelink.git

**Comment by esavary** [comment]
@acionca Did you also encounter this error after circumventing the SR research bug "18:27:42: Debug: window wxRichTextCtrl@0x55b09aae6110 ("text") lost focus even though it didn't have it" ?

**Comment by oesteban** [comment]
> @acionca Did you also encounter this error after circumventing the SR research bug "18:27:42: Debug: window wxRichTextCtrl@0x55b09aae6110 ("text") lost focus even though it didn't have it" ?

This sounds like a GTK/wxWidgets problem. Does it allow to continue or everything crashes?

**Comment by esavary** [comment]
Everything crashes at start. I tried following the SOPs procedure step by step to reinstall psychopy in my session + added your fix.

**Comment by esavary** [comment]
I'll try to reinstall the old version in my session.

**Comment by oesteban** [comment]
In my session it was working...

**Comment by esavary** [comment]
Yes that's why I think there's a step I didn't do right.  It looks like you've started to install the fix in the common session but I don't know if I'm missing some steps, I couldn't get it to work.Le 16 oct. 2023 19:28, Oscar Esteban ***@***.***> a écrit :
In my session it was working...

**Comment by acionca** [comment]
Ok, I managed to make it work with SR Research (by re-installing everything including [psychopy-eyetracker-eyelink](https://github.com/oesteban/psychopy-eyetracker-eyelink)). However, I am currently on Ubuntu 20.04.6 and never saw the bug: 
``` shell
Debug: window wxRichTextCtrl@0x55b09aae6110 ("text") lost focus even though it didn't have it
```

**Comment by oesteban** [comment]
Do you mean you are not getting this particular problem?

**Comment by acionca** [comment]
Correct, it's running on my side.

**Comment by oesteban** [comment]
And the reported version 20.04 is no mistake, correct?

**Comment by acionca** [comment]
Correct

**Comment by oesteban** [comment]
@esavary this looks like wxWidgets is not properly installed. In particular, I think this step: https://github.com/TheAxonLab/hcph-sops/pull/251/files#diff-f4e30b9174dbfc3032c3970cf1b6566f82be0de485f6bae70600302b89494cf7R2.

Please check:
- [ ] That the old wxWidgets (installed for 20.04) is not in use. I would say you need to uninstall it and then try the installation again, making sure that the version is the appropriate one
- [ ] Check that there are no other wxWidgets installations.
- [ ] If still a no-go, perhaps uninstall again, find the package un ubuntu's aptitude (apt-cache search wxwidgets) and install the necessary packages (I don't remember what is and what is not available).

**Comment by oesteban** [comment]
From here (https://wxpython.org/blog/2017-08-17-builds-for-linux-with-pip/index.html) an alternative to what we have in the SOPs could be:

0. Test step 6 with the current installation to see if there is a quick way of checking things.
1. Check you have all the required Ubuntu packages:
    > You will need the following packages (please consult your distribution's package list for the appropriate package names) and their dependencies:
    > 
    >     python3-dev
    >     libgtk-4-dev
    >     libgstreamer1.0-dev
    >     libgstreamer-plugins-base1.0-dev
    >     freeglut3-dev
    >     libwebkitgtk-6.0-dev
    >     libjpeg8-dev
    >     libpng
    >     libtiff
    >     libsdl
    >     libnotify
    >     libsm

    ```
    sudo apt install python3-dev libgtk-4-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev freeglut3-dev libwebkitgtk-6.0-dev libjpeg8-dev libpng-dev libtiff-dev libsdl1.2-dev libnotify-dev libsm-dev
    ```
2. (a) Create a virtual env
    ```
    python3 -m venv $HOME/psychopyenv
    source ~/psychopyenv/bin/activate
    ```
2. (b) Update necessary python packages:
    ```
    python -m pip install -U pip
    python -m pip install -U six wheel setuptools
    python -m pip install -U numpy
    ```
3. Download the wxPython sources:
    ```
    pip download wxPython
    ```
4. Build wxPython
    ```
    pip wheel -v wxPython-4.0.1.tar.gz  2>&1 | tee build.log
    ```
5. Install the wheel you just created:
    ```
    pip install wxPython-<version-of-package-and-python>-linux_x86_64.whl
    ```
6. Test the installation:
     ```
     python -c "import wx; a=wx.App(); wx.Frame(None,title='hello world').Show(); a.MainLoop();"
     ```

**Comment by esavary** [comment]
Ok, I'll try. @acionca , when you installed it, did you strictly follow the SOPs, or did you need to carry out any additional steps? And @oesteban, did you try running the tasks in addition to launching psychopy on your own session when you tested on Friday? If yes, were they running without bugs?

**Comment by acionca** [comment]
I strictly followed the SOPs. However, since I had to re-install a couple of time, it is possible that some steps were already done as I did not try on a "fresh Ubuntu".

**Comment by oesteban** [comment]
> And @oesteban, did you try running the tasks in addition to launching psychopy on your own session when you tested on Friday? If yes, were they running without bugs?

As I said, I had to go before testing everything together. It worked on my workstation (meaning, I successfully ran the fixation experiment). But did not test on the laptop.

Before you do anything else - does the experiment run with Python? (i.e., not opening psychopy).

What you want to do now is getting an understanding of what is failing. Is it a stale installation of the window library (GTK/wxWidgets/wxPython), is it a psychopy bug, or is it an interaction of the two?

The error:

```
Debug: window wxRichTextCtrl@0x55b09aae6110 ("text") lost focus even though it didn't have it
```

doesn't look like a terminal error. It looks more like something else failed and then wxWidgets gave this unexpected outcome. What the log under `$HOME/.psychopy3` says? To help, we need something more beyond "I don't know what steps I might not have done exactly like the SOPs".

**Comment by esavary** [comment]
No unfortunately it does the same when I run the experiment directly with python. I'm now following the steps you just posted.
Here is the log:
```
0.1306 	DEBUG 	Opening message catalog /home/esavary/.local/lib/python3.10/site-packages/psychopy/localization/../app/locale/en_US/LC_MESSAGE/messages.mo for locale en_US
PTB-INFO: Trying to suspend potentially running PulseAudio server... ... status 0
PTB-INFO: Using PortAudio V19.7.0-devel, revision unknown
/home/esavary/.local/lib/python3.10/site-packages/psychopy/app/coder/fileBrowser.py:167: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
  self.browseBtn.SetToolTipString(_translate(
/home/esavary/.local/lib/python3.10/site-packages/psychopy/app/coder/fileBrowser.py:172: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
  self.libRootBtn.SetToolTipString(_translate(
/home/esavary/.local/lib/python3.10/site-packages/psychopy/app/coder/fileBrowser.py:179: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
  self.currentFileBtn.SetToolTipString(_translate(
3.2124 	WARNING 	Speech-to-text recognition module for PocketSphinx is not available (use command `pip install SpeechRecognition` to get it). Transcription will be unavailable using that service this session.
3.2126 	WARNING 	Speech-to-text recognition using Google online services is not available (use command `pip install google-api-core google-auth google-cloud google-cloud-speech googleapis-common-protos` to get it). Transcription will be unavailable using that service this session.
3.2128 	ERROR 	Support for the `sounddevice` audio backend is not available this session. Please install `psychopy-sounddevice` and restart the session to enable support.
3.3133 	INFO 	Loaded psychtoolbox audio version 3.0.19.649712521
3.3135 	INFO 	sound is using audioLib: PTB
3.4613 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.4613 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.4613 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.4613 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.4613 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
4.1186 	DEBUG 	No PsychoPy plugin packages found in environment.
4.3750 	WARNING 	Couldn't connect to psychopy.org
Check internet settings (and proxy setting in PsychoPy Preferences.
```

**Comment by oesteban** [comment]
```
3.2128 	ERROR 	Support for the `sounddevice` audio backend is not available this session. Please install `psychopy-sounddevice` and restart the session to enable support.
```

**Comment by esavary** [comment]
It doesn't resolve the issue. I'm still encountering the error: `Debug: window wxRichTextCtrl@0x55b09aae6110 ("text") lost focus even though it didn't have it.` I'll follow the steps you've given and figure out a solution. I'll update the SOPs when I find the problem.

**Comment by oesteban** [comment]
What is the log now?

**Comment by esavary** [comment]
```
0.1115 	DEBUG 	Opening message catalog /home/esavary/.local/lib/python3.10/site-packages/psychopy/localization/../app/locale/en_US/LC_MESSAGE/messages.mo for locale en_US
PTB-INFO: Using PortAudio V19.7.0-devel, revision unknown
/home/esavary/.local/lib/python3.10/site-packages/psychopy/app/ribbon.py:363: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
  self.SetToolTipString(tooltip)
0.6725 	DEBUG 	User site-packages dir set to: /home/esavary/.psychopy3/packages/lib/python3.10/site-packages
2.6440 	DEBUG 	Looking for Tobii device configuration file...
2.6441 	DEBUG 	No Tobii device configuration file found.
2.6441 	DEBUG 	Looking for SR Research EyeLink device configuration file...
2.6577 	DEBUG 	Found SR Research EyeLink device configuration file.
2.6577 	DEBUG 	Looking for Gazepoint device configuration file...
2.6578 	DEBUG 	No Gazepoint device configuration file found.
2.6578 	DEBUG 	Looking for PupilLabs device configuration file...
2.6579 	DEBUG 	No PupilLabs device configuration file found.
3.3035 	INFO 	Trying to load audio library: sounddevice
3.3822 	INFO 	Loaded SoundDevice with PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4
3.3824 	INFO 	sound is using audioLib: sounddevice
3.3824 	WARNING 	We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
3.3914 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.3914 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.3915 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.3915 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.3915 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
3.4543 	DEBUG 	PavloviaLoggedIn
4.6882 	DEBUG 	No PsychoPy plugin packages found in environment.
5.0367 	WARNING 	Couldn't connect to psychopy.org
Check internet settings (and proxy setting in PsychoPy Preferences.
17.6960 	INFO 	Loaded monitor calibration from ['2023_01_10 14:21']
17.7203 	INFO 	Investigating repo at /home/esavary/workspace/HCPh-fMRI-tasks
17.7224 	WARNING 	We found a repository at /home/esavary/workspace/HCPh-fMRI-tasks but it doesn't point to gitlab.pavlovia.org. You could create that as a remote to sync from PsychoPy.
17.7235 	WARNING 	We found a repository at /home/esavary/workspace/HCPh-fMRI-tasks but it doesn't point to gitlab.pavlovia.org. You could create that as a remote to sync from PsychoPy.
Generating PsychoPy script...

## Running: /home/esavary/workspace/HCPh-fMRI-tasks/task-bht_bold_lastrun.py ###
```

**Comment by esavary** [comment]
And the error message `Debug: window wxRichTextCtrl@0x55b09aae6110 ("text") lost focus even though it didn't have it` is displayed in the terminal in which I run psychopy. I'm now doing the steps you provided, let me try this and I'll keep you updated.

**Comment by oesteban** [comment]
> ```
> 0.1115 	DEBUG 	Opening message catalog /home/esavary/.local/lib/python3.10/site-packages/psychopy/localization/../app/locale/en_US/LC_MESSAGE/messages.mo for locale en_US
> PTB-INFO: Using PortAudio V19.7.0-devel, revision unknown
> /home/esavary/.local/lib/python3.10/site-packages/psychopy/app/ribbon.py:363: wxPyDeprecationWarning: Call to deprecated item. Use SetToolTip instead.
>   self.SetToolTipString(tooltip)
> 0.6725 	DEBUG 	User site-packages dir set to: /home/esavary/.psychopy3/packages/lib/python3.10/site-packages
> 2.6440 	DEBUG 	Looking for Tobii device configuration file...
> 2.6441 	DEBUG 	No Tobii device configuration file found.
> 2.6441 	DEBUG 	Looking for SR Research EyeLink device configuration file...
> 2.6577 	DEBUG 	Found SR Research EyeLink device configuration file.
> 2.6577 	DEBUG 	Looking for Gazepoint device configuration file...
> 2.6578 	DEBUG 	No Gazepoint device configuration file found.
> 2.6578 	DEBUG 	Looking for PupilLabs device configuration file...
> 2.6579 	DEBUG 	No PupilLabs device configuration file found.
> 3.3035 	INFO 	Trying to load audio library: sounddevice
> 3.3822 	INFO 	Loaded SoundDevice with PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4
> 3.3824 	INFO 	sound is using audioLib: sounddevice
> 3.3824 	WARNING 	We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
> 3.3914 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
> 3.3914 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
> 3.3915 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
> 3.3915 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
> 3.3915 	WARNING 	image was set to update during ISI_load_images Static Component, but that component no longer exists
> 3.4543 	DEBUG 	PavloviaLoggedIn
> 4.6882 	DEBUG 	No PsychoPy plugin packages found in environment.
> 5.0367 	WARNING 	Couldn't connect to psychopy.org
> Check internet settings (and proxy setting in PsychoPy Preferences.
> 17.6960 	INFO 	Loaded monitor calibration from ['2023_01_10 14:21']
> 17.7203 	INFO 	Investigating repo at /home/esavary/workspace/HCPh-fMRI-tasks
> 17.7224 	WARNING 	We found a repository at /home/esavary/workspace/HCPh-fMRI-tasks but it doesn't point to gitlab.pavlovia.org. You could create that as a remote to sync from PsychoPy.
> 17.7235 	WARNING 	We found a repository at /home/esavary/workspace/HCPh-fMRI-tasks but it doesn't point to gitlab.pavlovia.org. You could create that as a remote to sync from PsychoPy.
> Generating PsychoPy script...
> 
> ## Running: /home/esavary/workspace/HCPh-fMRI-tasks/task-bht_bold_lastrun.py ###
> ```

This log is clear progress. You can see the eye tracker is now registered

**Comment by oesteban** [comment]
@esavary one more interesting output from your log:

```
0.6725 	DEBUG 	User site-packages dir set to: /home/esavary/.psychopy3/packages/lib/python3.10/site-packages
```

It is possible that this is tinkering with your Python installation. Perhaps, it would be useful to install wxWidgets after pointing python to this site-packages folder:

```
export USER_SITE=/home/esavary/.psychopy3/packages/lib/python3.10/site-packages
python -m pip install ...
```

A second thought is: are we talking about the common user or your user. This looks like you are working on your user (which is fine, but I'm less familiar with what you have under your username).

A third thought is: we don't want to *just make it work*. We want to *understand* what the problem is, *fix it* and as a consequence, *get it to work*. It is fundamental that we figure out the why in order to confidently use it knowing we will be able to fix everything should new problems emerge.

**Comment by esavary** [comment]
Yes, I'm actively trying to comprehend the issue, but time is running short because the BIDS conversion and event file preparations need to be completed by Thursday too. I'm focusing on resolving the problem within my user session first, and once I've established a stable solution, I'll apply it to the common user session as well. At the moment, the tasks run without the bug when wxWidgets is uninstalled. I'm currently investigating why this is the case and whether I can reinstall it without causing the tasks to crash.

**Comment by oesteban** [comment]
> At the moment, the tasks run without the bug when wxWidgets is uninstalled

I don't understand. It works when running with `python task-export.py` ?

**Comment by esavary** [comment]
The script runs with the command ` python name-of-the-task.py` (Even without wxwidget), but I'm now facing issues with 'pylink'. Specifically, I get an error: `AttributeError: module 'pylink' does not have the 'EyeLink' attribute.` The code doesn't crash but without this working we cannot communicate with the ET so I'm trying to fix this in priority.

**Comment by oesteban** [comment]
That is because the either or both pylink from the SR Research Ubuntu package or the plugin I created are not properly installed in the environment.
