### ISSUE TITLE
[SCAN] sub-001_ses-002

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/hcph-sops#276]
### Setup

- [X] Syncbox
- [X] Biopac
- [X] Gas analyzer
- [X] EyeTracker
- [X] PsychoPy
- [X] Acqknowledge
- [X] Respiration belt
- [X] ECG

### General notes

RB still flat...

### Anatomical scans completion

- [X] Localizer was completed.
- [X] Localizer looked okay.
- [X] T1w was completed.
- [X] T1w looked okay.

### Anatomical scans notes

Participant moved (a lot) after the T1w (adjustment of the respiration belt)

### Eye-tracker calibration completion

- [X] Eye-tracker calibration was completed.

### Diffusion scan completion

- [X] Diffusion was completed.

### Diffusion scan notes

RB still flat – we tried to calibrate after the scan and it didn't change anything

### Fieldmap scans completion

- [X] DWI was completed.
- [X] GRE was completed.
- [ ] EPI BOLD was completed.
- [ ] Physiological signals are still recording and look ok.

### Eye-tracker drift correction

- [X] Eye-tracker drift was corrected.

### Positive-control task completion

- [ ] Positive-control task was completed.
- [ ] Physiological signals are still recording and look ok.

### task-pct issues

interrupted scan

### Positive-control task notes

We stopped the acquisition and then couldn't start again. We decided to stop here and make things work on the next session.

### Resting-state completion

- [ ] Resting-state was completed.
- [ ] Physiological signals are still recording and look ok.

### Breath-holding task completion

- [ ] Breath-holding task was completed.

### T2w scan completion

- [ ] T2w scan was completed.

### Were all scans acquired successfully ?

- [ ] Yes, all went well.
