### ISSUE TITLE
Rewrite ET-to-BIDS conversion in the SOPs

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#342]
Update the following section of the SOPs:

https://github.com/TheAxonLab/hcph-sops/blob/91121e8e465e4e53427b0ad053aacc04bca58c50/docs/data-management/post-session.md#L288-L359

With the following goals:

- [ ] Clearly describe that we need to use a docker image of bidsphysio with @esavary's code. If there is a built image of this, please push it to docker hub so that we don't need to build it ourselves.
- [ ] Clearly state the command line necessary to convert the EDF file corresponding to a task.
- [ ] Include comments that are relevant regarding how to run it best.
- [ ] Indicate whatever clerical stuff (move files, rename files, complete metadata in JSONs) that is necessary.
- [ ] Add a schedule TSV file like those we have in `code/events/` and `code/physioconv/`, where session number, date, phase encoding direction and corresponding EDF files are listed (see [`code/events/schedule.tsv`](https://github.com/TheAxonLab/hcph-sops/blob/mkdocs/code/events/schedule.tsv) for the closest example of this)
