### ISSUE TITLE
Add the first session of ET data in BIDS to the dataset

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#343]
Following the steps of #342:

- [x] Convert one session into BIDS
- [x] Add the generated `_eyetrack.tsv.gz` and `_eyetrack.json` to the dataset.

EDIT - Additions after checking on the added data:

- [x] theaxonlab/hcph-dataset#2
- [x] theaxonlab/hcph-dataset#3
- [x] theaxonlab/hcph-dataset#4
- [x] theaxonlab/hcph-dataset#5

**Comment by esavary** [comment]
I did it yesterday. Is there any issue with the data?

**Comment by oesteban** [comment]
> I did it yesterday. Is there any issue with the data?

I'll check now. Can we address #342 before we call this resolved anyways?

**Comment by oesteban** [comment]
Thanks for this. Indeed, I was able to pull down the data!

I have written a few quick items that I've found and I think we want to address before this one can be closed. These are theaxonlab/hcph-dataset#2, theaxonlab/hcph-dataset#3, and theaxonlab/hcph-dataset#4.

That said, these three issues can wait -- let's keep the plans and focus on #342 now.

**Comment by esavary** [comment]
I've uploaded the eye-tracking (ET) data for session 1, generated with the latest code version. Can you confirm if everything appears to be in order?

Regarding calibration, I followed the draft [BIDS specification](https://bids-specification--1128.org.readthedocs.build/en/1128/modality-specific-files/eye-tracking.html), which allows setting CalibrationCount = 0 when no calibration has been performed for the run. I chose this approach because copying calibration data from another task might introduce inaccuracies due to drift. If you have alternative suggestions, I'm open to implementing them. 

The code I used to convert the data is in this PR #383.
