### ISSUE TITLE
Create a Jupyter notebook demonstrating ET conversion into BIDS

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#344]
A Jupyter notebook inspired by the one about physio and the one about events seems a reasonable way to define more specific and small steps toward #74 and facilitate finishing the conversion.

This notebook would complement the SOPs (i.e., please address #342 first) and use the outcomes of #343.

The notebook should have four sections, one for the DWI and three for each of the fMRI tasks. The structure of the sections is the same:

- [ ] Open the `_eyetrack.tsv.gz` file corresponding to the session.
- [ ] Plot the timeseries of the two coordinates with matplotlib, and plot below the timeseries of pupil diameter, deltas for eye blinks, etc.
- [ ] Plot a heatmap (joint histogram) of frequency (time spent) in each area of the 800x600 frame (similar to the eyelink visualization software).
