### ISSUE TITLE
Eye tracker to BIDS

### ISSUE THREAD

**Issue by oesteban** [TheAxonLab/hcph-sops#74]
We would want to see how to encode the eye-tracker outputs into BIDS ([see these guidelines for caveats and tips](https://www.fieldtriptoolbox.org/example/bids_eyetracker/)), and we can perhaps give a last push to https://github.com/bids-standard/bids-specification/pull/1128.

> [!WARNING]
> EDITED on 11 October 2023 to reflect conversations. See below this note.

This issue can be closed when we achieve the following:

- [ ] Generate BIDS-formatted ET data for one session, say `pilot020` (i.e., including diffusion and functional, if available), following the ET BEP linked above. This task includes addressing the issues in #235 .
- [ ] Figure out whether the calibration information can be retrieved from the eye tracker and store it as BIDS metadata #175.
- [ ] Address minor compliance issues such as #233.
- [ ] Once the above is checked out, finally generate BIDS-formatted ET data for all the sessions we have run so far.

> [!WARNING]
> EDITED on 8 November 2023 to try to break this issue down into pieces.
> Since progress has not translated into actionable items that could be ticked in the boxes above, I have been trying to define more specific and atomic actions toward completing this goal. Therefore, #342, #343, #344, and #345 have been opened to define the keystones to finish this. This issue will be closed as it is now redundant.

**Comment by oesteban** [comment]
time to revive this from the brainhack?

**Comment by oesteban** [comment]
something to have around - https://cran.r-project.org/web/packages/eyelinkReader/eyelinkReader.pdf

**Comment by oesteban** [comment]
Outcome of the brainhack: https://github.com/cbinyu/bidsphysio/pull/13

**Comment by celprov** [comment]
@oesteban @esavary I see a PR was merged mentioning this issue, has this been addressed?
Is this needed before the data collection?

**Comment by oesteban** [comment]
We have some initial results, but not without problems (#235).

**Comment by oesteban** [comment]
Replaced by the issues recently open to break this down into more digestible pieces. See warning note added to the issue message atop.
